session_name: chatSummary
api_id: "TODO"
api_hash: "TODO"
model_provider: openai # openai | groq | ollama
model_name: gpt-4o-mini # groq: llama-3.1-8b-instant, ollama: llama3.2
max_length: 4000
summarization_frequency: 24 # in hours
output_dir: summaries
summary_channel_id: -1234567890 # channel id where summaries will be posted
channels:
  - id: -1001235860760
    name: IT_TALKS_BENELUX
    language: russian
    context: "This is a channel for software engineers working in the Benelux region, discussing various topics. The channel contains a lot of non-serious discussion, but it's known to be useful for finding a job or getting real insights. "
    filters:
      keywords: ["tech", "benelux"]

  - id: -1001157394889
    name: LEETCODE_HEROES
    filters:
      keywords: ["leetcode", "interview"]
